version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "0:5432"

  web:
    build: .
    command: bin/rails server --port 80 --binding 0.0.0.0
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - .:/app
