default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  host: db

development:
  <<: *default
  database: materiais_development

test:
  <<: *default
  database: materiais_test

production:
  <<: *default
  database: materiais_production
