# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316c241ec4f71b4582e86ee29bba41e69df1040df560833a48fcaf8f28a69319419dd1d172813b338737e7542e045037640f1feab9f3da4a570c41820b794ec0

test:
  secret_key_base: ccecf7e7049f3b2e02872e521bfb631a153ee8fd2eddf76087ced3d188efe2a17d88a4be642df42ec19010bda5e35a8b7e42d79aeaf7dc9e6d05348d7f9b0934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
